export const testdata = [
  {
    title: 'Your home stock',
    data: [
      {key: 1, title: 'Apples'},
      {key: 2, title: 'Bananas'},
      {key: 3, title: 'Milk'},
      {key: 4, title: 'Eggs'},
      {key: 5, title: 'Bread'},
      {key: 6, title: 'Cheese'},
      {key: 7, title: 'Tomatoes'},
      {key: 8, title: 'Cucumbers'},
      {key: 9, title: 'Onions'},
      {key: 10, title: 'Potatoes'},
      {key: 11, title: 'Chicken'},
      {key: 12, title: 'Rice'},
      {key: 13, title: 'Pasta'},
      {key: 14, title: 'Spinach'},
      {key: 15, title: 'Carrots'},
      {key: 16, title: 'Oranges'},
      {key: 17, title: 'Yogurt'},
      {key: 18, title: 'Salmon'},
      {key: 19, title: 'Cereal'},
      {key: 20, title: 'Coffee'},
    ],
  },
  {
    title: 'Stock that needs refilling',
    data: [
      {key: 1, title: 'Apples'},
      {key: 2, title: 'Bananas'},
      {key: 3, title: 'Milk'},
      {key: 4, title: 'Eggs'},
      {key: 5, title: 'Bread'},
      {key: 6, title: 'Cheese'},
      {key: 7, title: 'Tomatoes'},
      {key: 8, title: 'Cucumbers'},
      {key: 9, title: 'Onions'},
      {key: 10, title: 'Potatoes'},
      {key: 11, title: 'Chicken'},
      {key: 12, title: 'Rice'},
      {key: 13, title: 'Pasta'},
      {key: 14, title: 'Spinach'},
      {key: 15, title: 'Carrots'},
      {key: 16, title: 'Oranges'},
      {key: 17, title: 'Yogurt'},
      {key: 18, title: 'Salmon'},
      {key: 19, title: 'Cereal'},
      {key: 20, title: 'Coffee'},
    ],
  },
];

export const data1 = [
  {key: 1, title: 'Apples'},
  {key: 2, title: 'Bananas'},
  {key: 3, title: 'Milk'},
  {key: 4, title: 'Eggs'},
  {key: 5, title: 'Bread'},
  {key: 6, title: 'Cheese'},
  {key: 7, title: 'Tomatoes'},
  {key: 8, title: 'Cucumbers'},
  {key: 9, title: 'Onions'},
  {key: 10, title: 'Potatoes'},
  {key: 11, title: 'Chicken'},
  {key: 12, title: 'Rice'},
  {key: 13, title: 'Pasta'},
  {key: 14, title: 'Spinach'},
  {key: 15, title: 'Carrots'},
  {key: 16, title: 'Oranges'},
  {key: 17, title: 'Yogurt'},
  {key: 18, title: 'Salmon'},
  {key: 19, title: 'Cereal'},
  {key: 20, title: 'Coffee'},
];

export const data2 = [
  {key: 1, title: 'Aspirin'},
  {key: 2, title: 'Bandages'},
  {key: 3, title: 'Syringe'},
  {key: 4, title: 'Antibiotics'},
  {key: 5, title: 'Face Mask'},
  {key: 6, title: 'Thermometer'},
  {key: 7, title: 'Cotton Swabs'},
  {key: 8, title: 'Painkillers'},
  {key: 9, title: 'Hand Sanitizer'},
  {key: 10, title: 'Gauze'},
  {key: 11, title: 'Prescription Medication'},
  {key: 12, title: 'Antiseptic Wipes'},
  {key: 13, title: 'Medical Gloves'},
  {key: 14, title: 'First Aid Kit'},
  {key: 15, title: 'Vitamins'},
  {key: 16, title: 'Cough Syrup'},
  {key: 17, title: 'Allergy Medication'},
  {key: 18, title: 'Eye Drops'},
  {key: 19, title: 'N95 Mask'},
  {key: 20, title: 'Blood Pressure Monitor'},
];
